apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pocdemo
  template:
    metadata:
      labels:
        app: pocdemo
    spec:
      containers:
      - name: pocdemo
        image: gcr.io/network-demo-293711/sampleimag:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pocdemo
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: pocdemo
