apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pocdemo
  template:
    metadata:
      labels:
        app: pocdemo
    spec:
      containers:
      - name: pocdemo
        image: gcr.io/network-demo-293711/sampleimag:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pocservice
spec:
  type: LoadBalancer
  selector:
    app: pocdemo
  ports:
  - protocol: TCP
    port: 9999
    targetPort: 8080
